### ISSUE TITLE
Investigate restoring UID range of source cluster's namespace to destination cluster and potential conflicts.

### ISSUE THREAD

**Issue by jwmatthews** [migtools/openshift-migration-plugin#20]
Related to https://github.com/fusor/openshift-migration-plugin/pull/8

When we migrate stateful applications from a source cluster to a destination cluster we need to be aware of the UIDs used by the applications on source side and preserve those UIDs on destination side to ensure that file system permissions line up.

For example, on the source side assume that a namespace has the annotations:
```
$ oc get namespace mssql-persistent -o yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
     .....
    openshift.io/sa.scc.mcs: s0:c23,c22
    openshift.io/sa.scc.supplemental-groups: 1000550000/10000
    openshift.io/sa.scc.uid-range: 1000550000/10000
    .......
```

When pods run in that namespace we assume the UID being used will be lower end of the `openshift.io/sa.scc.uid-range: 1000550000/10000`

We will migrate the contents of this namespace (all k8s resources and associated data in persistent volumes) to a destination cluster.

We are currently assuming that we migrate into a new namespace we create and we supply the annotations we want to use, so we would ensure we set the annotations of
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
     .....
    openshift.io/sa.scc.mcs: s0:c23,c22
    openshift.io/sa.scc.supplemental-groups: 1000550000/10000
    openshift.io/sa.scc.uid-range: 1000550000/10000
    .......
```
Desire is for the pods when they run on destination side and access their data in PVs (which was migrated from source) the file system permissions will line up.

Question is, do we need to be concerned that another namespace on the cluster may already be using that uid-range `1000550000/10000`?

Is there a hard requirement that namespaces in OpenShift __must__ use unique uid-ranges?  

In the case that some other namespace exists on the destination cluster and was already using something that overlapped/contained or contained `1000550000/10000` would this result in a problem?
