### ISSUE TITLE
imagestreamplugin: sort based on generation

### ISSUE THREAD

**Issue by alaypatel07** [migtools/openshift-migration-plugin#68]
```
  - items:
    - created: "2020-07-17T14:46:03Z"
      dockerImageReference: docker.io/alaypatel07/ruby-hello-world@sha256:173646699fdcfe7c1bca741cb545cf4409046dc2315898466533db694da2d2b5
      generation: 4
      image: sha256:173646699fdcfe7c1bca741cb545cf4409046dc2315898466533db694da2d2b5
    - created: "2020-07-17T01:24:06Z"
      dockerImageReference: docker.io/alaypatel07/ruby-hello-world@sha256:8c392e72bdcf42cb3d051007797d7272c42934594da18d42ddce8d40bd99e6b6
      generation: 3
      image: sha256:8c392e72bdcf42cb3d051007797d7272c42934594da18d42ddce8d40bd99e6b6
    tag: alias
```
for the same tag, the current logic to transfer the image is to reverse the order and push the oldest image first. Instead of assuming that reversing the order will produce the right output, I wonder if we can sort the list based on `generation` value to come up with a consistent list of images generated in order w.r.t. time

**Comment by alaypatel07** [comment]
```
status:
  dockerImageRepository: docker-registry.default.svc:5000/image-benchmark/time
  tags:
  - items:
    - created: "2020-07-17T01:06:57Z"
      dockerImageReference: docker-registry.default.svc:5000/image-benchmark/time@sha256:e657280d6bb690c4eb2e1384598cba802fe29a77bacea86889194ac1cc4d4be3
      generation: 1
      image: sha256:e657280d6bb690c4eb2e1384598cba802fe29a77bacea86889194ac1cc4d4be3
    - created: "2020-07-17T01:04:20Z"
      dockerImageReference: docker-registry.default.svc:5000/image-benchmark/time@sha256:253c98ed23b04b7062b5fabea19ecff1808ae0f74da6b05d6979fc179bbf6f09
      generation: 1
      image: sha256:253c98ed23b04b7062b5fabea19ecff1808ae0f74da6b05d6979fc179bbf6f09
    tag: latest
```

I dont understand how that works, especially both generation being 1
